SET SQL DIALECT 3;

/* CREATE DATABASE '127.0.0.1/gds_db:Embedediblite' USER 'SYSDBA' password 'Enter Password here' PAGE_SIZE 4096
 WITH ADMIN OPTION
 DEFAULT CHARACTER SET  */
COMMIT;
/* Users in Database (passwords need to be added)*/
/* CREATE USER MANAGER SET PASSWORD /* Password needed */  SYSTEM USER NAME 'Manager';*/
/* CREATE USER STAFF SET PASSWORD /* Password needed */  SYSTEM USER NAME 'Staff';*/
/*CONNECT '127.0.0.1/gds_db:Embedediblite' USER 'SYSDSO' PASSWORD 'Enter Password here'*/
/* ALTER DATABASE SET SYSTEM ENCRYPTION PASSWORD 'Enter Password here';*/
COMMIT;

/* Table: LOG_ENTRIES, Owner: SYSDBA */

CREATE TABLE "LOG_ENTRIES" 
(
  "PROJ_ID"	INTEGER NOT NULL,
  "PICTURE"	BLOB SUB_TYPE 0 SEGMENT SIZE 80 NOT NULL,
  "LONGITUDE"	FLOAT,
  "LATITUDE"	FLOAT,
  "TIMEDATESTAMP"	TIMESTAMP,
  "OR_X"	FLOAT NOT NULL,
  "OR_Y"	FLOAT NOT NULL,
  "OR_Z"	FLOAT NOT NULL,
  "OR_DISTANCE"	FLOAT NOT NULL,
  "HEADING_X"	FLOAT NOT NULL,
  "HEADING_Y"	FLOAT NOT NULL,
  "HEADING_Z"	FLOAT NOT NULL,
  "V_X"	FLOAT NOT NULL,
  "V_Y"	FLOAT NOT NULL,
  "V_Z"	FLOAT NOT NULL,
  "ANGLE_X"	FLOAT NOT NULL,
  "ANGLE_Y"	FLOAT NOT NULL,
  "ANGLE_Z"	FLOAT NOT NULL,
  "MOTION"	FLOAT NOT NULL,
  "SPEED"	FLOAT NOT NULL,
  "NOTE"	BLOB SUB_TYPE TEXT SEGMENT SIZE 80
);

/* Table: PROJECTS, Owner: SYSDBA */

CREATE TABLE "PROJECTS" 
(
  "PROJ_ID"	INTEGER NOT NULL,
  "PROJ_TITLE"	VARCHAR(30) NOT NULL,
  "PROJ_DESC"	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
 PRIMARY KEY ("PROJ_ID")
);
ALTER TABLE "LOG_ENTRIES" ADD FOREIGN KEY ("PROJ_ID") REFERENCES "PROJECTS" ("PROJ_ID") ON UPDATE SET DEFAULT ON DELETE SET DEFAULT;

CREATE GENERATOR "GENAUTOINC";
/* Subscriptions */
COMMIT WORK;

/* Stored procedures */

COMMIT WORK;

/* Triggers only will work for SQL triggers */

CREATE TRIGGER "AUTOINC" FOR "PROJECTS" 
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  new."PROJ_ID" = gen_id(GENAUTOINC,1);
end
 ;

COMMIT WORK ;

/* Grant Roles for this database */


/* Role: "MGMTROLE", Owner: SYSDBA */

CREATE ROLE "MGMTROLE";
CREATE ROLE "STAFFROLE";

/* Grant permissions for this database */

GRANT "MGMTROLE" TO MANAGER;

GRANT "STAFFROLE" TO STAFF;

